---
development:
  cloud_name: dmsqgzztx
  api_key: '856245218448971'
  api_secret: F8aO4mOefcyRX8qoG6QTwk3Od_I
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dmsqgzztx
  api_key: '856245218448971'
  api_secret: F8aO4mOefcyRX8qoG6QTwk3Od_I
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dmsqgzztx
  api_key: '856245218448971'
  api_secret: F8aO4mOefcyRX8qoG6QTwk3Od_I
  enhance_image_tag: true
  static_image_support: false
